# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/083b4204-2474-4847-b8e9-1021c5d8e3d6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b491f485-9a90-4028-b3e3-753e14bfc20f".device = "/dev/disk/by-uuid/b491f485-9a90-4028-b3e3-753e14bfc20f";
  boot.initrd.luks.devices."luks-e2b011ab-8c73-493d-9197-403af9675c93".device = "/dev/disk/by-uuid/e2b011ab-8c73-493d-9197-403af9675c93";


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3570-E65E";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/616627e5-7bd5-413b-ae4d-2a173e7db92a"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
